### PR TITLE
feature: select output device

### PR DESCRIPTION
**Pull request by jacksonvieiracs**
Add speak select #5

image

limitations

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/sinkId

### CODE REVIEW

**Comment by jacksonvieiracs** [comment]
@brunocroh I made some merge commits without rebase, if you need clean the commits let me know.

**Comment by brunocroh** [comment]
First of firsts, thank you for your contribution.

Could you, please, change the input positions?

image

I believe we can have the following order Audio Input, Audio output and so Video Input.

Microphone | Headphone | Camera

**Comment by brunocroh** [comment]
I fixed the input order, but build is failing, we need to take a look on it before merge

**Comment by brunocroh** [comment]
Thanks for your contribution @Jackson-Vieira , I really appreciate it

**Review by brunocroh — COMMENTED** [review]
LGTM

**Comment by jacksonvieiracs** [comment]
Hi @brunocroh , thanks for the changes and tips, I was a little off due to work, I'll be back to contribute soon

**Pull request merged**
